services:
  - type: web
    name: koksu-market-backend
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn marketday_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Or appropriate version
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false # Set this in Render dashboard
